[package]
name = "pgrep"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linked-hash-map = "0.5.4"
termcolor = "1.1.2"
regex = "1.5.4"
